[package]
name = "ratzilla"
version = "0.2.0"
description = "Build terminal-themed web applications with Ratatui and WebAssembly"
authors = ["Orhun ParmaksÄ±z <orhunparmaksiz@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/ratatui/ratzilla"
repository = "https://github.com/ratatui/ratzilla"
keywords = ["tui", "webassembly", "ratatui"]
categories = ["wasm"]
include = ["src/**/*", "Cargo.*", "LICENSE", "README.md", "CHANGELOG.md"]
edition = "2021"

[dependencies]
web-sys = { version = "0.3.81", features = [
    'console',
    'CanvasRenderingContext2d',
    'Document',
    'Element',
    'HtmlCanvasElement',
    'HtmlElement',
    'KeyboardEvent',
    'Location',
    'MouseEvent',
    'Navigator',
    'Node',
    'Performance',
    'Screen',
    'WebGl2RenderingContext',
    'WebGlBuffer',
    'WebGlProgram',
    'WebGlRenderingContext',
    'WebGlShader',
    'WebGlTexture',
    'WebGlUniformLocation',
    'WebGlVertexArrayObject',
    'Window',
] }
compact_str = "0.9.0"
ratatui = { version = "0.30", default-features = false, features = ["all-widgets", "layout-cache"] }
console_error_panic_hook = "0.1.7"
thiserror = "2.0.12"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc", "std"] }
beamterm-renderer = "0.10.0"
unicode-width = "0.2.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.56"
